### ISSUE TITLE
Do we have confirmation that we can change the CNK codes? Should be a

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/medication#144]
Do we have confirmation that we can change the CNK codes? Should be a
decision by the Working Group (because the decision to use cnk... was also).
https://cnk.apb.be/codings/cnk_product_codes

**Comment by costateixeira** [comment]
Indeed, my formulation was perhaps misleading.
This is indeed a technical issue with some impact on terminology so we just
have to run it with the group.
The decision to change the namingsystem url to ehealth.fgov..... (if that
is what we are discussing) should be simple within he working group

**Comment by bdc-ehealth** [comment]
Mail was sent out with deadline 30/05/2022 to the medication workgroup, and no objections have come in.
