### ISSUE TITLE
Reason for ATC codes

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/medication#152]
Hi. Does anyone remember why ATC codes were added? 
Unless there was a specific request from the project, I am not sure what is the idea there. 

@bdc-ehealth @jmp-ehealth @KarlienHL7Belgium 

https://github.com/hl7-be/medication/commit/ad383ecc8dd12e66a7984b31744f46af1fe374ce

**Comment by JensPenny** [comment]
This is on the medication dispense profile. I'll just attempt to reconstruct a couple of things I vaguely remember here, but just to preface this: I'm ok with not modelling ATC on the dispense but moving it to the medication. With that being said: \

- ATC is a concept talked about in this [medication concepts document](https://docs.google.com/document/d/1rTGHvdNMZfR4MZvVVIfUnoAi8eDQsYTpcKBB3B8q4JI/edit#heading=h.h7vvfbjcot2s)
  - I feel personally that we shouldn't model this, but treat this as a valueset and a property of the medication-definition itself, whatever that may be. 
- Currently I **think** vaccinations can be directly administered in vaccinnet by ATC, or there might be support for this either way. Nowadays most registrations happen on CNK. There is a third possible identifier which is a vaccinnet identifier, but I haven't seen this in the wild.

**Comment by costateixeira** [comment]
Agreed to remove ATC as additional codings. May be added in the future as classifications

**Comment by bdc-ehealth** [comment]
@costateixeira , @annenerenhausen,

ATC is 




































































































@costateixeira , @annenerenhausen,

ATC is still present in the business rules, we should definitely clarify this:

Product/Substance	1 .. 1	Est le nom du médicament/substance. Il sera défini par un n° unique (CTI-extended -> CNK -> ATC) tel qu’on peut le trouver dans la source authentique des médicaments SAM V2.	Medication	Y

**Comment by costateixeira** [comment]
This issue was resolved and agreed. ATC had been added as a coding, which is not established in the document, and is not really a good thing. We agreed to remove since examples are not normative and this example was incorrect/misleading. @bdc-ehealth please open another issue if you have any concrete suggestions to bring to the group.

**Comment by bdc-ehealth** [comment]
@costateixeira This is a legitimate comment. The business rules document is not in line with the IG. @annenerenhausen Could you remove ATC from the business rules document. It is in the interest of the Belgian software community and industry that business documents and technical artifacts are aligned.

**Comment by costateixeira** [comment]
ATC still makes sense as a classification.
The issue was doing it as a coding, in the examples. That issue is now
resolved. Please create another issue if you want to stimulate any further
discussion. For the WG, this issue is closed.
