### ISSUE TITLE
Mapping kmehr -> fhir?

### ISSUE THREAD

**Issue by pablocorilus** [hl7-be/medication#163]
@costateixeira @bdc-ehealth any progress is this ?

**Comment by JensPenny** [comment]
This also means that the implementation of a mapping gets pushed to each vendor I assume?  

For the record: I have no issue with that, I just want this clarified. 
If that is the case I feel like this issue can be closed as well.

**Comment by bdc-ehealth** [comment]
@JensPenny ,

I do not want to make any statements on who will implement "a" mapping. The point is that the resulting FHIR will have to be confirmed by a physician, because an automatic translation that is always correct, is mathematically not feasible.
