### ISSUE TITLE
There is lacking info in sushi-config.yaml

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/medication#180]
Sushi: error SUSHI minimally requires the following configuration properties to generate an IG: canonical, fhirVersion, id, name, status, copyrightYear, releaseLabel. (00:00.011 / 00:01.520, 97Mb)
Sushi:   File: sushi-config.yaml

**Comment by costateixeira** [comment]
this was temporary while fixing QA, fixed now
