### ISSUE TITLE
Example MedicationDispense: Medication Dispense Example 1 / Add example - several medication with the same sguid and different dguid()

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/medication#50]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| Example MedicationDispense: Medication Dispense Example 1 | Add example - several medication with the same sguid and different dguid | JCT |  | HL7.BE.FHIR.MEDICATIONIG\Medication Dispense Example 1 - FHIR v4.0.1 |

**Comment by costateixeira** [comment]
both example1 and example2 have a same sguid and different dguids
