### ISSUE TITLE
Resource Profile: BeMedicationDispense - Examples / Add example - 2 meds: Antibiotic (prescription 1) and Dafalgan (prescription 2) - Same SGUID, different DGUIDs.()

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/medication#54]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| Resource Profile: BeMedicationDispense - Examples | Add example - 2 meds: Antibiotic (prescription 1) and Dafalgan (prescription 2) - Same SGUID, different DGUIDs. | JCT |  | HL7.BE.FHIR.MEDICATIONIG\Profile - Medication Dispense - Examples - FHIR v4.0.1 |

**Comment by costateixeira** [comment]
duplicate issue - see #43 and #50
