### ISSUE TITLE
Formal Views of Profile Content / Indication should be 0..*()

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/medication#88]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| Formal Views of Profile Content | Indication should be 0..* | JCT |  | HL7.BE.FHIR.MEDICATIONIG\Logical Model Medication Record - FHIR v4.0.1 |

**Comment by costateixeira** [comment]
reason is 0..* in the updated model
