### ISSUE TITLE
Formal Views of Profile Content / Add a note on treatment line (possibly a duplicate or reference)()

### ISSUE THREAD

**Issue by hl7belgium-technicaluser** [hl7-be/medication#89]
| Document | Section | Comment | Organization Name | Mail |
|---|---|---|---|---|
| Formal Views of Profile Content | Add a note on treatment line (possibly a duplicate or reference) | JCT |  | HL7.BE.FHIR.MEDICATIONIG\Logical Model Medication Record - FHIR v4.0.1 |

**Comment by costateixeira** [comment]
there's a note on Medication Line already.
